### PR TITLE
Chore: Adding alias as dev for solo command

### PR DESCRIPTION
**Pull request by MrPunyapal**

### CODE REVIEW

**Comment by aarondfrancis** [comment]
I dunno, this feels like it might conflict with other commands? Does anyone else have opinions here?

**Comment by mergehez** [comment]
Writing "solo" is not so difficult that you would need to add an alias for it.

**Comment by MrPunyapal** [comment]
Of course it's not hard to write solo while running the command but something like `php artisan run:dev`  feels like you are running the app!

**Comment by aarondfrancis** [comment]
I think I'll hold off on this for now! Thanks for the idea though

**Pull request closed without merging**
