### PR TITLE
feat: allow non-standard namespace for SoloServiceProvider

### PR DESCRIPTION
**Pull request by eleftrik**
If your `SoloServiceProvider` is stored in a namespace which is not the standard `App\Providers`, Laravel Solo is gonna "complain" because commands are being registered from an unsafe location.

This PR adds the method `useCustomNamespaceProvider`, which tells Laravel Solo to consider it as a safe location to register commands from.

This method takes the service provider instance itself as an argument of `AaronFrancis\Solo\Providers\SoloApplicationServiceProvider` type (which your service provider is subclass of): this ensures that the user is not trying to register as safe an arbitrary class namespace.

Example:

```php
namespace App\Custom\Namespace\Providers;

use AaronFrancis\Solo\Commands\EnhancedTailCommand;
use AaronFrancis\Solo\Facades\Solo;
use AaronFrancis\Solo\Providers\SoloApplicationServiceProvider;

class SoloServiceProvider extends SoloApplicationServiceProvider
{
    public function register()
    {
        Solo::useTheme('dark')
            // Call before registering commands!
            ->useCustomNamespaceProvider($this)
            // Commands that auto start.
            ->addCommands([
                EnhancedTailCommand::make('Logs', 'tail -f -n 100 ' . storage_path('logs/laravel.log')),
                'Vite' => 'npm run dev',
                // 'HTTP' => 'php artisan serve',
                'About' => 'php artisan solo:about'
            ])
            // Not auto-started
            ->addLazyCommands([
                'Queue' => 'php artisan queue:listen --tries=1',
                // 'Reverb' => 'php artisan reverb:start',
                // 'Pint' => 'pint --ansi',
            ])
            // FQCNs of trusted classes that can add commands.
            ->allowCommandsAddedFrom([
                //
            ]);
    }

    public function boot()
    {
        //
    }
}
```

### CODE REVIEW

**Comment by aarondfrancis** [comment]
This seems like a good solution. Where do you normally store your service providers if not App\Providers?

**Comment by eleftrik** [comment]
@aarondfrancis I use a domain-driven oriented folder structure inspired by Spatie's "Laravel beyond CRUD", at least for medium-sized applications.

In short: `src/App/Support/Providers/SoloServiceProvider.php`.

**Comment by aarondfrancis** [comment]
@eleftrik do you still have an App\Providers\AppServiceProvider in this setup?

**Comment by aarondfrancis** [comment]
@eleftrik I changed it up a bit! Let me know what you think

**Review by aarondfrancis — APPROVED** [review]

**Pull request merged**
